server:
  host: 0.0.0.0
  port: 9090
log:
  level: debug
  format: json
  logDir: "/data/logs"

mysql:
  master:
    host: master
    port: 3306
    username: master
    password: master666
    database: master

  slave:
    host: slave
    port: 3306
    username: slave
    password: slave666
    database: slave


